// Generated by uniffi-bindgen-react-native
#include "quic-relay-client.h"
#include "generated/quic_relay_client.hpp"

namespace quicrelayclient {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeQuicRelayClient::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}