// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "quic-relay-client.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "QuicRelayClientSpec.h"

@interface QuicRelayClient : NSObject <NativeQuicRelayClientSpec>
#else
#import <React/RCTBridgeModule.h>

@interface QuicRelayClient : NSObject <RCTBridgeModule>
#endif

@end