/**
 * Local, on-device cache of each contact's `username`, keyed by their
 * permanent `user_id` (issue #174). Exists solely so a message sender's
 * display name is available for a push notification without a network
 * round-trip, and (issue #239) so a notification tap can open `Chat`, which
 * is keyed by `{ userId, username }`, with no network call. This is not a
 * general-purpose contact directory; `email` is intentionally not stored.
 *
 * Shares the same on-device SQLite database (`storage/messages.ts`'s
 * `DATABASE_NAME`) and the same `drizzle-kit`-generated migrations folder as
 * `messages.ts`, per docs/decisions/0012-mobile-local-storage-uses-drizzle-going-forward.md
 * -- `schema.ts` is the single source of truth for every table in this
 * database, `drizzle/` the single migrations folder for all of them. Calling
 * `migrate()` here again (already done once by `messages.ts`) is a safe
 * no-op once every migration has been applied: drizzle-orm tracks applied
 * migrations in the database itself (`__drizzle_migrations`), not per
 * module.
 */
import * as SQLite from 'expo-sqlite';
import { drizzle } from 'drizzle-orm/expo-sqlite';
import { migrate } from 'drizzle-orm/expo-sqlite/migrator';
import { eq } from 'drizzle-orm';
// Generated by `npm run db:generate`; lives at the app root alongside
// drizzle.config.ts, not under src/.
import migrations from '../../drizzle/migrations';
import { contacts as contactsTable } from './schema';
import { DATABASE_NAME } from './messages';

/** One contact as returned by `GET /api/contacts` -- only the fields this
 * cache needs (`user_id`/`username`), so callers don't need to import the
 * full mobile `Contact` type just to upsert. */
export interface CacheableContact {
  userId: string;
  username: string;
}

const sqliteDb = SQLite.openDatabaseSync(DATABASE_NAME);
const db = drizzle(sqliteDb, { schema: { contacts: contactsTable } });

// Mirrors `messages.ts`'s pattern: migrations are kicked off once here and
// every exported function awaits this shared promise before touching the
// database.
const migrationsReady: Promise<void> = migrate(db, migrations);

/**
 * Upserts each contact into the local cache: inserts a row for a `userId`
 * not already present, updates `username` for a `userId` already present
 * (a user can change their username later, per issue #184). Intended to be
 * called with the full list returned by a successful contacts fetch.
 * Local rows for contacts no longer in `contacts` (e.g. removed
 * server-side) are left in place -- pruning is out of scope for this
 * cache (see issue #174's "Out of scope").
 */
export async function upsertContacts(contactsList: CacheableContact[]): Promise<void> {
  await migrationsReady;
  for (const contact of contactsList) {
    await db
      .insert(contactsTable)
      .values({ userId: contact.userId, username: contact.username })
      .onConflictDoUpdate({
        target: contactsTable.userId,
        set: { username: contact.username },
      });
  }
}

/**
 * Returns the cached `username` for `userId`, or `null` if that `userId`
 * isn't cached. Reads only from local SQLite -- never makes a network call,
 * so this is safe to use from a context with no connectivity (the whole
 * point of this cache).
 */
export async function getCachedContactUsername(userId: string): Promise<string | null> {
  await migrationsReady;
  const rows = await db
    .select({ username: contactsTable.username })
    .from(contactsTable)
    .where(eq(contactsTable.userId, userId))
    .limit(1);
  return rows[0]?.username ?? null;
}
