/**
 * Local, on-device message history store backed by `expo-sqlite` via
 * `drizzle-orm`'s `expo-sqlite` driver, with schema evolution handled by
 * real `drizzle-kit` migrations (see `src/storage/schema.ts`,
 * `drizzle.config.ts`, and the generated `drizzle/` migrations folder) per
 * docs/decisions/0012-mobile-local-storage-uses-drizzle-going-forward.md.
 * This is the only place chat message content is stored durably on the
 * client (see docs/decisions/0001-message-content-never-in-postgres.md for
 * why the backend never persists it). Independent of any screen so it can
 * be unit tested in isolation.
 *
 * `body` is plaintext UTF-8 text (per
 * docs/decisions/0007-local-history-stores-plaintext.md) — a plain SQLite
 * `TEXT` column, not base64-wrapped. This module never inspects or
 * transforms it beyond that.
 */
import * as SQLite from 'expo-sqlite';
import { drizzle } from 'drizzle-orm/expo-sqlite';
import { migrate } from 'drizzle-orm/expo-sqlite/migrator';
import { and, asc, eq, isNull, sql } from 'drizzle-orm';
// Generated by `npm run db:generate`; lives at the app root alongside
// drizzle.config.ts, not under src/.
import migrations from '../../drizzle/migrations';
import { messages as messagesTable } from './schema';

export const DATABASE_NAME = 'epistl.db';

export type MessageDirection = 'outgoing' | 'incoming';

export interface StoredMessage {
  id: number;
  contactUserId: string;
  direction: MessageDirection;
  body: string;
  createdAt: string;
}

export interface SaveMessageInput {
  contactUserId: string;
  direction: MessageDirection;
  body: string;
  createdAt: string;
}

/**
 * One row per contact, summarizing that contact's most recent message and
 * whether they have any unread incoming messages. Backs the Conversations
 * screen's list.
 */
export interface ConversationSummary {
  contactUserId: string;
  lastBody: string;
  lastDirection: MessageDirection;
  lastCreatedAt: string;
  hasUnread: boolean;
}

interface ConversationSummaryRow {
  contact_user_id: string;
  body: string;
  direction: MessageDirection;
  created_at: string;
  has_unread: number;
}

// One row per contact_user_id: the most recent message (by created_at, with
// id as a tiebreaker), plus whether that contact has any unread incoming
// message. Grouped via a window function rather than fetch-all-then-group in
// JS so this scales with message count instead of contact count in memory.
// Drizzle's query builder has no window-function support, so this uses the
// raw-SQL escape hatch (`db.all`) rather than the builder.
const GET_CONVERSATION_SUMMARIES_SQL = sql<ConversationSummaryRow>`
WITH ranked AS (
  SELECT
    contact_user_id,
    body,
    direction,
    created_at,
    ROW_NUMBER() OVER (
      PARTITION BY contact_user_id
      ORDER BY created_at DESC, id DESC
    ) AS rn
  FROM messages
),
unread AS (
  SELECT DISTINCT contact_user_id
  FROM messages
  WHERE direction = 'incoming' AND read_at IS NULL
)
SELECT
  ranked.contact_user_id AS contact_user_id,
  ranked.body AS body,
  ranked.direction AS direction,
  ranked.created_at AS created_at,
  CASE WHEN unread.contact_user_id IS NOT NULL THEN 1 ELSE 0 END AS has_unread
FROM ranked
LEFT JOIN unread ON unread.contact_user_id = ranked.contact_user_id
WHERE ranked.rn = 1
ORDER BY ranked.created_at DESC
`;

interface SearchMessagesRow {
  contact_user_id: string;
}

/**
 * Builds a `messages_fts` `MATCH` argument from a free-text search query,
 * per SQLite's FTS5 query syntax
 * (https://sqlite.org/fts5.html#full_text_query_syntax): each whitespace-
 * separated term is double-quoted (escaping any embedded `"`) so bareword
 * FTS5 query-syntax operators typed by the user (`-foo`, `foo*`, `NEAR`,
 * unbalanced `"`, etc.) are treated as literal text to search for rather
 * than parsed as FTS5 syntax, and ANDed together (FTS5's default when
 * multiple quoted strings are juxtaposed).
 */
function toFtsMatchQuery(query: string): string {
  return query
    .split(/\s+/)
    .filter((term) => term.length > 0)
    .map((term) => `"${term.replace(/"/g, '""')}"`)
    .join(' AND ');
}

const sqliteDb = SQLite.openDatabaseSync(DATABASE_NAME);
const db = drizzle(sqliteDb, { schema: { messages: messagesTable } });

// `migrate()` is async, and top-level await isn't available under the
// CommonJS output Metro/Jest produce, so migrations are kicked off once
// here and every exported function awaits this shared promise before
// touching the database (all of them are already async, so this doesn't
// change their signatures).
const migrationsReady: Promise<void> = migrate(db, migrations);

function rowToMessage(row: typeof messagesTable.$inferSelect): StoredMessage {
  return {
    id: row.id,
    contactUserId: row.contactUserId,
    direction: row.direction,
    body: row.body,
    createdAt: row.createdAt,
  };
}

function rowToConversationSummary(row: ConversationSummaryRow): ConversationSummary {
  return {
    contactUserId: row.contact_user_id,
    lastBody: row.body,
    lastDirection: row.direction,
    lastCreatedAt: row.created_at,
    hasUnread: row.has_unread === 1,
  };
}

/** Inserts one message row. */
export async function saveMessage(input: SaveMessageInput): Promise<void> {
  await migrationsReady;
  await db.insert(messagesTable).values({
    contactUserId: input.contactUserId,
    direction: input.direction,
    body: input.body,
    createdAt: input.createdAt,
  });
}

/**
 * Deletes every message row, across every contact. The `messages_ad`
 * trigger (`drizzle/0001_messages_fts.sql`) keeps `messages_fts` in sync
 * automatically, so no separate FTS cleanup is needed here. Used by the
 * delete-account flow (`SettingsScreen`, issue #92), which only calls this
 * after the server has confirmed the account itself is gone; never by
 * log-out, which deliberately leaves local chat history intact so logging
 * back in as the same user finds it unchanged.
 */
export async function clearAllMessages(): Promise<void> {
  await migrationsReady;
  await db.delete(messagesTable);
}

/** Returns all messages for a contact, ordered by `created_at` ascending. */
export async function getMessages(contactUserId: string): Promise<StoredMessage[]> {
  await migrationsReady;
  const rows = await db
    .select()
    .from(messagesTable)
    .where(eq(messagesTable.contactUserId, contactUserId))
    .orderBy(asc(messagesTable.createdAt));
  return rows.map(rowToMessage);
}

/**
 * Marks every unread incoming message from `contactUserId` as read, setting
 * `read_at` to the current timestamp. Outgoing rows and rows for other
 * contacts are untouched. Safe to call repeatedly (a no-op once there is
 * nothing unread left).
 */
export async function markContactMessagesRead(contactUserId: string): Promise<void> {
  await migrationsReady;
  await db
    .update(messagesTable)
    .set({ readAt: new Date().toISOString() })
    .where(
      and(
        eq(messagesTable.contactUserId, contactUserId),
        eq(messagesTable.direction, 'incoming'),
        isNull(messagesTable.readAt)
      )
    );
}

/**
 * Returns one summary per contact — their most recent message and whether
 * they have any unread incoming messages — ordered by most recent message
 * first.
 */
export async function getConversationSummaries(): Promise<ConversationSummary[]> {
  await migrationsReady;
  const rows = await db.all<ConversationSummaryRow>(GET_CONVERSATION_SUMMARIES_SQL);
  return rows.map(rowToConversationSummary);
}

/**
 * Full-text searches message content via the `messages_fts` FTS5 virtual
 * table (see `drizzle/0001_messages_fts.sql` and
 * `drizzle/0002_light_karnak.sql`, which re-points it at the plaintext
 * `body` column), returning the distinct contacts with at least one
 * matching message. Returns `[]` for a blank (empty/whitespace-only) query
 * rather than running a query FTS5 would reject.
 */
export async function searchMessages(query: string): Promise<{ contactUserId: string }[]> {
  await migrationsReady;
  const matchQuery = toFtsMatchQuery(query.trim());
  if (matchQuery === '') {
    return [];
  }
  const rows = await db.all<SearchMessagesRow>(sql<SearchMessagesRow>`
    SELECT DISTINCT m.contact_user_id AS contact_user_id
    FROM messages_fts
    JOIN messages m ON m.id = messages_fts.rowid
    WHERE messages_fts MATCH ${matchQuery}
  `);
  return rows.map((row) => ({ contactUserId: row.contact_user_id }));
}
